### ISSUE TITLE
Scaling - Profile2 Image

### ISSUE THREAD

**Issue by goeranhomberg** [Th-Da/thomas-danielse.de#1]
The Profile2-Image should not scale horizontally when the screen width is increasing above 2000px.

![image](https://user-images.githubusercontent.com/17685156/208653478-8bdb0ed3-f5ef-4c98-9f27-3253c48b6ac8.png)

**Comment by Th-Da** [comment]
@goeranhomberg thank you for reporting. The issue is fixed.
